# DOCKERHUB_IMAGE：打包的 docker 镜像地址
# DOCKERHUB_LOGIN_USER：docker hun 用户名
# DOCKERHUB_LOGIN_PASSWORD：docker hub 密码
# TENCENT_CLOUD_SSHKEY：云服务器 ssh 秘钥

name: Spring boot workflow

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name:
      - name: Docker flow
        run: |
        docker login -u ${{ secrets.DOCKERHUB_LOGIN_USER }} -p ${{ secrets.DOCKERHUB_LOGIN_PASSWORD }}
        docker build -t ${{ secrets.DOCKERHUB_IMAGE }} .
        docker push ${{ secrets.DOCKERHUB_IMAGE }}
      - name: deploy service on remote server
        uses: appleboy/ssh-action@master
        with:
          host: '212.64.41.111'
          username: 'ubuntu'
          key: ${{ secrets.TENCENT_CLOUD_SSHKEY }}
          script: |
            whoami
            ls -al
